### PR TITLE
Update gacela version

### PR DESCRIPTION
**Pull request by Chemaclass**
### 🔖 Changes

- Update gacela to 0.11
- Clean ups the DependencyProviders removing the unnecessary return types from the closures

### CODE REVIEW

**Comment by jenshaase** [comment]
To fix the error you maybe need to call `Registry::getInstance()->clear()` before the tests

**Comment by Chemaclass** [comment]
In the `ReaderTest`, right?

**Comment by jenshaase** [comment]
Yes

**Comment by jenshaase** [comment]
Thanks. I merged it.

**Pull request merged**
