### PR TITLE
Add contains-value? function

### PR DESCRIPTION
**Pull request by Chemaclass**
## 🤔 Background

I think it would be practical if we have a function that checks if a value is inside a collection. Similar as the `contains?` 🤔 

## 🔖 Changes

- Add `contains-value?` function

### CODE REVIEW

**Review by JesusValera — APPROVED** [review]

**Comment by jenshaase** [comment]
`array_flip` only works with string and integer values. It is not working for something like this:
```
(contains-value? [:a :b] :a)
```

Also the current implementation is not working for maps:
```
(contains-value? {:a 1 :b 2} 1) # => error
```

I would suggest to solve this problem with existing Phel functions only. Maybe the `for` loop is an option.

**Comment by jenshaase** [comment]
Isn't the `find` function basically what you are looking for? Don't know how it behaves on maps, but you can combine it with the `values` function and it should work.

**Comment by Chemaclass** [comment]
That's a good idea. Actually changing the function to this helps a lot:
```lisp
(defn contains-value?
  "Returns true if value is present in the given collection, otherwise returns false."
  [coll val]
  (if (empty? coll)
    false
    (not (nil? (find |(= $ val) coll)))))
```
And all the tests that I wrote pass, but not these two:
```lisp
(is (false? (contains-value? (set 1) 2)))
(is (true? (contains-value? (set 1) 1)))
```

Screenshot 2022-10-21 at 19 46 02

Any idea why are only these two tests failing? 🤔 
What do you think about the new implementation of the `contains-value?` using `find`, @jenshaase?

**Comment by jenshaase** [comment]
I would suggest to wrap `coll` with the `values` function. This will then also support maps.

```
(defn contains-value?
  "Returns true if value is present in the given collection, otherwise returns false."
  [coll val]
  (if (empty? coll)
    false
    (not (nil? (find |(= $ val) (values coll))))))
```

**Comment by Chemaclass** [comment]
@jenshaase, thanks! Code updated 👌🏻

**Comment by jenshaase** [comment]
Could you add tests for maps?

**Comment by Chemaclass** [comment]
Sure thing, @jenshaase. Done.

**Pull request merged**
