### PR TITLE
Add contributor-covenant code of conduct

### PR DESCRIPTION
**Pull request by Chemaclass**
## 📚 Description

Add basic code of conduct for the project
https://contributor-covenant.org

> I got the inspiration by PHPUnit's code of conduct: https://github.com/sebastianbergmann/phpunit/blob/master/.github/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by jenshaase** [comment]
Is there a reason you suggest to use version 1.3 and not the latest version 2.1?

**Comment by Chemaclass** [comment]
Ups, no, I didn't notice there is a 2.1. I will update it!

**Review by JesusValera — APPROVED** [review]
Honestly, I think this is not really important, but green light for me :)

**Comment by Chemaclass** [comment]
I think it's "kinda important" for an OSS project that wants to standardize and help the community to engage and feel welcomed, and it costs nothing to us to have such a thing in the project. I do agree that it's a nice to have, rather than a must, so why not? 😄

**Review by jenshaase — APPROVED** [review]

**Pull request merged**
